
before:
  hooks:
    - go mod tidy

builds:
- env:
    - CGO_ENABLED=0

  ldflags:
    - '-X main.Version={{.Version}}'

  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - arm64

  # Build reproducible
  mod_timestamp: '{{ .CommitTimestamp }}'

  # Binary name.
  binary: go-dnscollector

archives:
- id: zipformat
  format: zip
  rlcp: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - config.yml
    
- id: targzformat
  format: tar.gz
  rlcp: true
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  files:
    - config.yml

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256