openapi: 3.0.2
info:
  title: Swagger for DNS-collector tool
  version: 0.28.0
  description: This is a swagger for the API of the DNS-collector.
  contact:
    email: d.machard@gmail.com
  license:
    name: MIT
    url: 'https://github.com/dmachard/go-dns-collector/blob/main/LICENSE'
  x-logo:
    url: ''
servers:
  - url: 'http://localhost:8080/'
paths:
  /search:
    get:
      parameters:
        - in: query
          name: stream_id
          schema:
            type: string
          description: stream identity name
        - in: query
          name: query_ip
          schema:
            type: string
          description: query ip to search
        - in: query
          name: query_name
          schema:
            type: string
          description: query name to search
      responses:
        '200':
          description: Return list of domains founded
          content:
            text/plain:
              schema:
                type: string
      summary: Return a list of domains
  /streams:
    get:
      responses:
        '200':
          description: Return list of streams id
          content:
            text/plain:
              schema:
                type: string
      summary: Return list of streams id
  /clients:
    get:
      responses:
        '200':
          description: Return full list of clients
          content:
            text/plain:
              schema:
                type: string
      summary: Return full list of clients 
  /clients/top:
    get:
      responses:
        '200':
          description: Top source ip clients
          content:
            text/plain:
              schema:
                type: string
      summary: Top source ip clients
  /domains:
    get:
      responses:
        '200':
          description: Return full list of domains
          content:
            text/plain:
              schema:
                type: string
      summary: Return full list of domains
  /domains/top:
    get:
      responses:
        '200':
          description: Top domains list
          content:
            text/plain:
              schema:
                type: string
      summary: Top domains list
  /domains/nx:
    get:
      responses:
        '200':
          description: Return full list of NX domains
          content:
            text/plain:
              schema:
                type: string
      summary: Return full list of NX domains
  /domains/nx/top:
    get:
      responses:
        '200':
          description: Top NX domains list
          content:
            text/plain:
              schema:
                type: string
      summary: Top NX domains list
  /domains/servfail:
    get:
      responses:
        '200':
          description: Return full list of SERVFAIL domains
          content:
            text/plain:
              schema:
                type: string
      summary: Return full list of SERVFAIL domains
  /domains/servfail/top:
    get:
      responses:
        '200':
          description: Top SERVFAIL domains
          content:
            text/plain:
              schema:
                type: string
      summary: Return Top SERVFAIL domains
  /tlds:
    get:
      responses:
        '200':
          description: Return full list of top level domains
          content:
            text/plain:
              schema:
                type: string
      summary: Return full list of top level domains
  /tlds/top:
    get:
      responses:
        '200':
          description: Top first level domains list
          content:
            text/plain:
              schema:
                type: string
      summary: Top first level domains list
  /suspicious:
    get:
      responses:
        '200':
          description: Rerurn suspicious domains list
          content:
            text/plain:
              schema:
                type: string
      summary: Return suspicious domains list         
security: []
externalDocs:
  url: 'https://github.com/dmachard/go-dns-collector'