name: go build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  go-ubuntu:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: ['1.19', '1.20']

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: build binary
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o go-dnscollector *.go

  go-macos:
    runs-on: macos-latest
    
    strategy:
      matrix:
        go-version: [ '1.19', '1.20' ]
        
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: build binary
      run: CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o go-dnscollector *.go

  go-win:
    runs-on: windows-latest
    
    strategy:
      matrix:
        go-version: [ '1.19', '1.20' ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: build binary
      run: |
        set CGO_ENABLED=0
        go build -o go-dnscollector.exe .
      
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build --build-arg VERSION=dev . --file Dockerfile -t go-dnscollector
